||eclick.vn^
||admicro.vn^
||admicro*.vcmedia.vn^
||adi.vcmedia.vn^
||vcplayer.vcmedia.vn^
||video-thumbs.vcmedia.vn^
||static.hosting.vcmedia.vn^
||adnetwork.vn^
||adtimaserver.vn^
||ad360.vn^
||anthill.vn^
||ants.vn^
||polyad.net
||epi.vn^
||ambient-platform.com^
||st.f1.vnecdn.net^
||f37.img.vnecdn.net^
||f38.img.vnecdn.net^
||shop.vnecdn.net^
||raovat.vnecdn.net^
||imgraovat.vnecdn.net^
||straovat.vnecdn.net^
||raovat.vnexpress.net^
||shop.vnexpress.net^
||imgshop.vnexpress.net^
||imgraovat.vnexpress.net^
||s.tuoitre.vn^	
||quangcao.thanhnien.vn^
||thongke.24h.com.vn^
||24hstatic.com^
||game.24h.com.vn^
||log.news.zing.vn^
||fptad.com^
||mookie1.com^
||sparkling.vn^
||stc.nas.nixcdn.com^
||a1515150.com^
||novanet.vn^
||vimobi.com^
||channelvn.net^
||ad.org.vn^
||adap.tv^
